name: Update BEL20 Data

on:
  schedule:
    - cron: '*/10 * * * *' # Dit zorgt ervoor dat het script elke 10 minuten draait
  workflow_dispatch: # Hiermee kun je het ook handmatig starten via het 'Actions' tabblad

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install yfinance

      - name: Run update script
        run: python update.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m "Automatische data update: $(date)" || echo "Geen wijzigingen om te committen"
          git push
